CREATE TABLE IF NOT EXISTS ORDERING (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT,
  status VARCHAR(255) NOT NULL,

  CONSTRAINT ORDERING_PK PRIMARY KEY (id),
  FOREIGN KEY (client_id) REFERENCES CLIENT (id)
);


--Order is a reserved keyword in database management system, that's why ORDERING