CREATE TABLE IF NOT EXISTS ORDERING_MEAL (
  ORDERING_id BIGINT,
  meal_id BIGINT,

  CONSTRAINT PK_ORDERING_MEAL PRIMARY KEY (ordering_id, meal_id),
  FOREIGN KEY (ordering_id) REFERENCES ORDERING (id) ON DELETE CASCADE,
  FOREIGN KEY (meal_id) REFERENCES MEAL (id) ON DELETE CASCADE
);
